### ISSUE TITLE
question - PLC connection timeout

### ISSUE THREAD

**Issue by MaelDanSel** [aphyt/omron_fins#1]
Hi thanks for this code, 
I was wondering if it was possible to add a parameter to set the connection **timeout** in TCPFinsConnection.connect ?

**Comment by aphyt** [comment]
Added to version 1.0.4 which is available here or on PyPi.

Example of connecting with a 2 second timeout is below. If a timeout is not specified, the default of using OS timeouts is used. After connection, the timeout is reverted to the OS timeout.

```Python
import fins.tcp

fins_instance = fins.tcp.TCPFinsConnection()
fins_instance.connect('192.168.250.17', connection_timeout=2)
```

**Comment by MaelDanSel** [comment]
Thank you so much you were quick.
